name: firebase_auth_ui
description: A new Flutter package project.
version: 0.0.1
author:
homepage: http://github.com/invertase/flutterfire_ui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_sign_in: ^4.5.3
  flutter_twitter_login: ^1.1.0
  flutter_facebook_auth: ^0.2.4
  github_sign_in: ^0.0.3
  country_code_picker: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_auth: any


